### ISSUE TITLE
dhcp-boot=tag:UEFI,efi64/bootx64.efi

### ISSUE THREAD

**Issue by idle4you** [cyberang3l/how-to-install-pxe-server-on-tomato#1]
Correct the mistake!

In this scenario, the computer will not boot in UEFI mode ...
You do not have such a bootx64.efi file

dhcp-boot=tag:UEFI,efi64/bootx64.efi

and you are copying the syslinux.efi file, so you need to fix it so that it is like this:

dhcp-boot=tag:UEFI,efi64/syslinux.efi

**Comment by cyberang3l** [comment]
Thank you for the comment! Fixed
